### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ajrothwell** [CityOfPhiladelphia/layerboard#3]
- [x] alphabetize
- [x] Add in yellow the same what Atlas had (demo) (immediate)
- [x] Make the map controller the same as Atlas
- [x] Legend scale dependency
- [x] i information button (metadata).  put it by the checkbox
- [ ] call to action
- [ ] Add the Atlas Measure tool (optional)
- [x] only one popup for mulitple features.  See RCOs
- [ ] routing, is there a way from atlas to click on and rco and link to a feature in this map with the layer on
- [ ] call to action above filtering box
